### ISSUE TITLE
ViewModel functions are not being called from the cloned div

### ISSUE THREAD

**Issue by lonormaly** [aliok/ion-affix#2]
Let's say I have this button:
<button class="button button-clear button-positive" ng-click="vm.sendCommandToPlayer('PrevAW');"></button>

vm.sendCommandToPlayer is a function defined within the controller using Controller as vm format.

On the cloned button, the function is not being called.

**Comment by aliok** [comment]
Fixed. Gonna be in 1.0.1.

**Comment by wbell** [comment]
Nice. Was just having issues with this, copied the latest from master, works as expected :thumbsup:

**Comment by lonormaly** [comment]
Thanks so much!

**Comment by aliok** [comment]
Released 1.0.1.
